name: Build docker image

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v[0-9]+.[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.1.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            eduhub-docker-production.artie.ia.surfsara.nl/ooapi-demo-data-server
            cr.surf.nl/oeapi-demodata/demodata
          tags: |
            type=match,pattern=v\d+.\d+
            type=sha,format=long
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: eduhub-docker-production.artie.ia.surfsara.nl
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: cr.surf.nl
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Sign image with a key
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
